// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMkRGZFiFuaiccEa5GCjMamhuEr-ca8-4',
    appId: '1:849660590954:web:09038c859092b83bde4313',
    messagingSenderId: '849660590954',
    projectId: 'myfirstapp-f4222',
    authDomain: 'myfirstapp-f4222.firebaseapp.com',
    storageBucket: 'myfirstapp-f4222.appspot.com',
    measurementId: 'G-THZHH02VGF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCogmya543Xdr4OqMBvpAGwGMO_YItcS8o',
    appId: '1:849660590954:android:bf86c40054eb7f67de4313',
    messagingSenderId: '849660590954',
    projectId: 'myfirstapp-f4222',
    storageBucket: 'myfirstapp-f4222.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDa5GF_jHVzKIQch4mp7QWZ7BLOobRE9Jk',
    appId: '1:849660590954:ios:35f4f95ff1b2ac56de4313',
    messagingSenderId: '849660590954',
    projectId: 'myfirstapp-f4222',
    storageBucket: 'myfirstapp-f4222.appspot.com',
    iosClientId: '849660590954-h6b97j4dq4m1p7ca6ete493p0oif2j3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDa5GF_jHVzKIQch4mp7QWZ7BLOobRE9Jk',
    appId: '1:849660590954:ios:35f4f95ff1b2ac56de4313',
    messagingSenderId: '849660590954',
    projectId: 'myfirstapp-f4222',
    storageBucket: 'myfirstapp-f4222.appspot.com',
    iosClientId: '849660590954-h6b97j4dq4m1p7ca6ete493p0oif2j3m.apps.googleusercontent.com',
    iosBundleId: 'com.example.myFirstApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAMkRGZFiFuaiccEa5GCjMamhuEr-ca8-4',
    appId: '1:849660590954:web:a813163f4ece9b40de4313',
    messagingSenderId: '849660590954',
    projectId: 'myfirstapp-f4222',
    authDomain: 'myfirstapp-f4222.firebaseapp.com',
    storageBucket: 'myfirstapp-f4222.appspot.com',
    measurementId: 'G-48VMQ1MM8C',
  );
}
